on: pull_request
name: build
jobs:
  pr-pipeline:
    name: Pull Request Pipeline
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Go
        uses: actions/setup-go@v1
        with: 
          go-version: 1.13

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Lint Go code
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin 
          go get -u golang.org/x/lint/golint 
          golint -set_exit_status

    
